#!/usr/bin/env python

import os
import subprocess
import sys
import argparse
import curses

def main():
	begin_x = 20
	begin_y = 7
	height = 5
	width = 40
	win = curses.newwin(height, width, begin_y, begin_x)

stdscr = curses.initscr()

curses.noecho()

curses.cbreak()

stdscr.keypad(1)



#-------------

do_main(stdscr)



#-------------



curses.nocbreak()

stdscr.keypad(0)

curses.echo()

curses.endwin()

